//
//  MeshWriter.swift
//  Lidar Scan (二次开发)
//
//  多格式导出器：OBJ / PLY / STL / GLB / USDZ。
//  - OBJ / PLY / GLB 支持带顶点点色与点云
//  - STL 为纯三角面（自动计算面法线）
//  - USDZ 走 ModelIO，带法线与颜色
//

import Foundation
import simd
import Metal
import MetalKit
import ModelIO

enum MeshWriter {

    // MARK: - 统一入口

    static func write(_ data: ScanMeshData,
                      kind: ScanContentKind,
                      format: ScanExportFormat,
                      to url: URL) throws {
        guard !data.isEmpty else { throw ScanExportError.noMeshData }

        switch format {
        case .obj:
            try writeOBJ(data, kind: kind, to: url)
        case .ply:
            try writePLY(data, kind: kind, to: url)
        case .stl:
            guard kind == .mesh else { throw ScanExportError.pointCloudNotSupported(.stl) }
            try writeSTL(data, to: url)
        case .glb:
            try writeGLB(data, kind: kind, to: url)
        case .usdz:
            guard kind == .mesh else { throw ScanExportError.pointCloudNotSupported(.usdz) }
            try writeUSDZ(data, to: url)
        }
    }

    // MARK: - OBJ

    private static func writeOBJ(_ data: ScanMeshData,
                                 kind: ScanContentKind,
                                 to url: URL) throws {
        var text = "# LiDAR Scan export\n"
        text += "# generated by Lidar Scan (SwiftUI)\n"
        text += "g scan\n"

        let hasColor = (data.colors != nil)
        if hasColor {
            for v in data.coloredVertices {
                text += String(format: "v %.3f %.3f %.3f %.2f %.2f %.2f\n",
                               v.vertex.x, v.vertex.y, v.vertex.z,
                               min(max(v.color.x, 0), 1),
                               min(max(v.color.y, 0), 1),
                               min(max(v.color.z, 0), 1))
            }
        } else {
            for v in data.vertices {
                text += String(format: "v %.3f %.3f %.3f\n", v.x, v.y, v.z)
            }
        }

        if kind == .mesh {
            // 法线兜底：缺失或全零时按面重建（否则 f a//a 引用空法线 → 着色发暗/文件非法）
            var normals = data.normals
            if normals.count != data.vertices.count {
                normals = computeFaceNormals(vertices: data.vertices, faces: data.faces)
            } else {
                let hasNonZero = normals.contains { simd_length($0) > 0.5 }
                if !hasNonZero {
                    normals = computeFaceNormals(vertices: data.vertices, faces: data.faces)
                }
            }
            for n in normals {
                text += String(format: "vn %.3f %.3f %.3f\n", n.x, n.y, n.z)
            }
            var faceLines = ""
            var idx = 0
            while idx + 2 < data.faces.count {
                let a = data.faces[idx] + 1
                let b = data.faces[idx + 1] + 1
                let c = data.faces[idx + 2] + 1
                faceLines += "f \(a)//\(a) \(b)//\(b) \(c)//\(c)\n"
                idx += 3
            }
            text += faceLines
        }

        try text.data(using: .utf8)?.write(to: url)
    }

    // MARK: - PLY (ASCII)

    private static func writePLY(_ data: ScanMeshData,
                                 kind: ScanContentKind,
                                 to url: URL) throws {
        var text = "ply\n"
        text += "format ascii 1.0\n"
        text += "comment generated by Lidar Scan\n"
        text += "element vertex \(data.vertexCount)\n"
        text += "property float x\n"
        text += "property float y\n"
        text += "property float z\n"
        text += "property uchar red\n"
        text += "property uchar green\n"
        text += "property uchar blue\n"
        if kind == .mesh {
            text += "element face \(data.faceCount)\n"
            text += "property list uchar int vertex_indices\n"
        }
        text += "end_header\n"

        // 顶点（颜色 0-255）
        var body = ""
        for v in data.coloredVertices {
            let r = Int((min(max(v.color.x, 0), 1) * 255).rounded())
            let g = Int((min(max(v.color.y, 0), 1) * 255).rounded())
            let b = Int((min(max(v.color.z, 0), 1) * 255).rounded())
            body += String(format: "%.5f %.5f %.5f %d %d %d\n", v.vertex.x, v.vertex.y, v.vertex.z, r, g, b)
        }

        if kind == .mesh {
            var idx = 0
            while idx + 2 < data.faces.count {
                body += "3 \(data.faces[idx]) \(data.faces[idx + 1]) \(data.faces[idx + 2])\n"
                idx += 3
            }
        }

        try (text + body).data(using: .utf8)?.write(to: url)
    }

    // MARK: - STL (ASCII)

    private static func writeSTL(_ data: ScanMeshData, to url: URL) throws {
        var text = "solid scan\n"
        var idx = 0
        while idx + 2 < data.faces.count {
            let a = data.vertices[Int(data.faces[idx])]
            let b = data.vertices[Int(data.faces[idx + 1])]
            let c = data.vertices[Int(data.faces[idx + 2])]

            let ab = SIMD3(b.x - a.x, b.y - a.y, b.z - a.z)
            let ac = SIMD3(c.x - a.x, c.y - a.y, c.z - a.z)
            var normal = SIMD3(ab.y * ac.z - ab.z * ac.y,
                               ab.z * ac.x - ab.x * ac.z,
                               ab.x * ac.y - ab.y * ac.x)
            let len = simd_length(normal)
            if len > 1e-6 { normal /= len } else { normal = SIMD3(0, 0, 1) }

            text += String(format: "facet normal %.6f %.6f %.6f\n", normal.x, normal.y, normal.z)
            text += "  outer loop\n"
            text += String(format: "    vertex %.5f %.5f %.5f\n", a.x, a.y, a.z)
            text += String(format: "    vertex %.5f %.5f %.5f\n", b.x, b.y, b.z)
            text += String(format: "    vertex %.5f %.5f %.5f\n", c.x, c.y, c.z)
            text += "  endloop\n"
            text += "endfacet\n"
            idx += 3
        }
        text += "endsolid scan\n"

        try text.data(using: .utf8)?.write(to: url)
    }

    // MARK: - GLB (二进制 glTF 2.0)

    private static func writeGLB(_ data: ScanMeshData,
                                 kind: ScanContentKind,
                                 to url: URL) throws {
        let vertices = data.coloredVertices
        let count = vertices.count
        let isMesh = (kind == .mesh)
        let indexCount = isMesh ? data.faces.count : 0

        // ---- 二进制数据 ----
        var bin = Data()
        let posOffset = bin.count
        for v in vertices {
            bin.appendFloats([v.vertex.x, v.vertex.y, v.vertex.z])
        }
        let normalOffset = bin.count
        bin.pad4()
        for v in vertices {
            bin.appendFloats([v.normal.x, v.normal.y, v.normal.z])
        }
        let colorOffset = bin.count
        bin.pad4()
        for v in vertices {
            let r = Float(min(max(v.color.x, 0), 1))
            let g = Float(min(max(v.color.y, 0), 1))
            let b = Float(min(max(v.color.z, 0), 1))
            bin.appendFloats([r, g, b])
        }
        let indexOffset = bin.count
        bin.pad4()
        if isMesh {
            for index in data.faces {
                bin.appendLE(index)
            }
        }

        // ---- 包围盒（POSITION accessor 需要 min/max）----
        var minV = SIMD3<Float>(repeating: .greatestFiniteMagnitude)
        var maxV = SIMD3<Float>(repeating: -.greatestFiniteMagnitude)
        for v in vertices {
            minV = simd_min(minV, v.vertex)
            maxV = simd_max(maxV, v.vertex)
        }

        // ---- JSON ----
        var bufferViews: [[String: Any]] = []
        var accessors: [[String: Any]] = []

        func addBufferView(offset: Int, length: Int) -> Int {
            bufferViews.append([
                "buffer": 0,
                "byteOffset": offset,
                "byteLength": length,
            ])
            return bufferViews.count - 1
        }

        func addAccessor(_ dict: [String: Any]) -> Int {
            accessors.append(dict)
            return accessors.count - 1
        }

        let posBV = addBufferView(offset: posOffset, length: count * 12)
        _ = addAccessor([
            "bufferView": posBV,
            "componentType": 5126, // FLOAT
            "count": count,
            "type": "VEC3",
            "min": [Double(minV.x), Double(minV.y), Double(minV.z)],
            "max": [Double(maxV.x), Double(maxV.y), Double(maxV.z)],
        ])

        let normalBV = addBufferView(offset: normalOffset, length: count * 12)
        _ = addAccessor([
            "bufferView": normalBV,
            "componentType": 5126,
            "count": count,
            "type": "VEC3",
        ])

        let colorBV = addBufferView(offset: colorOffset, length: count * 12)
        _ = addAccessor([
            "bufferView": colorBV,
            "componentType": 5126,
            "count": count,
            "type": "VEC3",
        ])

        var indexAccessor: Int?
        if isMesh {
            let indexBV = addBufferView(offset: indexOffset, length: indexCount * 4)
            indexAccessor = addAccessor([
                "bufferView": indexBV,
                "componentType": 5125, // UNSIGNED_INT
                "count": indexCount,
                "type": "SCALAR",
            ])
        }

        var attributes: [String: Any] = ["POSITION": 0, "COLOR_0": 2]
        if isMesh { attributes["NORMAL"] = 1 }

        var primitive: [String: Any] = [
            "attributes": attributes,
            "mode": isMesh ? 4 : 0, // TRIANGLES / POINTS
        ]
        if let indexAccessor = indexAccessor {
            primitive["indices"] = indexAccessor
        }
        if isMesh {
            primitive["material"] = 0
        }

        let json: [String: Any] = [
            "asset": ["version": "2.0", "generator": "LiDAR Scan"],
            "buffers": [["byteLength": bin.count]],
            "bufferViews": bufferViews,
            "accessors": accessors,
            "materials": [[
                "name": "scan",
                "doubleSided": true,
                "pbrMetallicRoughness": ["baseColorFactor": [1, 1, 1, 1]],
            ]],
            "meshes": [[
                "name": "scan",
                "primitives": [primitive],
            ]],
            "nodes": [["mesh": 0]],
            "scenes": [["nodes": [0]]],
            "scene": 0,
        ]

        // ---- 组装 GLB ----
        var jsonData = try JSONSerialization.data(withJSONObject: json, options: [])
        jsonData.pad4(with: 0x20)
        bin.pad4(with: 0x00)

        var header = Data()
        header.append(contentsOf: Array("glTF".utf8))
        header.appendLE(UInt32(2))                       // version
        header.appendLE(UInt32(12 + 8 + jsonData.count + 8 + bin.count)) // total length

        var out = header
        out.appendLE(UInt32(jsonData.count))
        out.append(contentsOf: Array("JSON".utf8))
        out.append(jsonData)
        out.appendLE(UInt32(bin.count))
        out.append(contentsOf: Array("BIN\u{0}".utf8))  // 'BIN\0'
        out.append(bin)

        try out.write(to: url)
    }

    // MARK: - USDZ (ModelIO)

    private static func writeUSDZ(_ data: ScanMeshData, to url: URL) throws {
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw ScanExportError.exportFailed("Metal 设备不可用")
        }

        // 法线兜底：全零时按面片重新计算
        var normals = data.normals
        if normals.count == data.vertexCount {
            let nonZero = normals.contains { simd_length($0) > 1e-6 }
            if !nonZero { normals = computeFaceNormals(vertices: data.vertices, faces: data.faces) }
        } else {
            normals = computeFaceNormals(vertices: data.vertices, faces: data.faces)
        }

        let allocator = MTKMeshBufferAllocator(device: device)

        // 交错顶点缓冲：Position(12B) + Normal(12B) + Color(12B) = 36B
        var vertexBytes: [Float] = []
        vertexBytes.reserveCapacity(data.vertexCount * 9)
        for i in 0..<data.vertexCount {
            let p = data.vertices[i]
            let n = normals[i]
            let c = data.colors?[i] ?? .meshGray
            vertexBytes.append(p.x); vertexBytes.append(p.y); vertexBytes.append(p.z)
            vertexBytes.append(n.x); vertexBytes.append(n.y); vertexBytes.append(n.z)
            vertexBytes.append(c.x); vertexBytes.append(c.y); vertexBytes.append(c.z)
        }
        var vertexData = Data()
        vertexData.appendFloats(vertexBytes)
        let vertexBuffer = allocator.newBuffer(with: vertexData, type: .vertex)

        var indexData = Data()
        for index in data.faces { indexData.appendLE(index) }
        let indexBuffer = allocator.newBuffer(with: indexData, type: .index)

        let submesh = MDLSubmesh(indexBuffer: indexBuffer,
                                 indexCount: data.faces.count,
                                 indexType: .uInt32,
                                 geometryType: .triangles,
                                 material: nil)

        let descriptor = MDLVertexDescriptor()
        descriptor.attributes[0] = MDLVertexAttribute(name: MDLVertexAttributePosition,
                                                      format: .float3, offset: 0, bufferIndex: 0)
        descriptor.attributes[1] = MDLVertexAttribute(name: MDLVertexAttributeNormal,
                                                      format: .float3, offset: 12, bufferIndex: 0)
        descriptor.attributes[2] = MDLVertexAttribute(name: MDLVertexAttributeColor,
                                                      format: .float3, offset: 24, bufferIndex: 0)
        descriptor.layouts[0] = MDLVertexBufferLayout(stride: 36)

        let mesh = MDLMesh(vertexBuffer: vertexBuffer,
                           vertexCount: data.vertexCount,
                           descriptor: descriptor,
                           submeshes: [submesh])

        let asset = MDLAsset()
        asset.add(mesh)
        try asset.export(to: url)
    }

    // MARK: - 工具

    /// 根据面片计算顶点法线（邻接三角形法线平均）
    static func computeFaceNormals(vertices: [SIMD3<Float>],
                                   faces: [UInt32]) -> [SIMD3<Float>] {
        var normals = [SIMD3<Float>](repeating: .zero, count: vertices.count)
        var idx = 0
        while idx + 2 < faces.count {
            let a = Int(faces[idx])
            let b = Int(faces[idx + 1])
            let c = Int(faces[idx + 2])
            if a < vertices.count, b < vertices.count, c < vertices.count {
                let va = vertices[a]
                let vb = vertices[b]
                let vc = vertices[c]
                let ab = SIMD3(vb.x - va.x, vb.y - va.y, vb.z - va.z)
                let ac = SIMD3(vc.x - va.x, vc.y - va.y, vc.z - va.z)
                var n = SIMD3(ab.y * ac.z - ab.z * ac.y,
                              ab.z * ac.x - ab.x * ac.z,
                              ab.x * ac.y - ab.y * ac.x)
                let len = simd_length(n)
                if len > 1e-6 { n /= len } else { n = SIMD3(0, 1, 0) }
                normals[a] += n
                normals[b] += n
                normals[c] += n
            }
            idx += 3
        }
        for i in 0..<normals.count {
            let len = simd_length(normals[i])
            if len > 1e-6 { normals[i] /= len }
        }
        return normals
    }
}